#!/usr/bin/env bash
set -ue

APPNAME=${1:-"nora"}
STACK=${2:-"windows"}

## Remove existing
cf d -f $APPNAME

## Push new
cf push $APPNAME -s $STACK -b java_buildpack -p NoraPublished --no-start
cf set-env $APPNAME DIEGO_BETA true 
cf set-env $APPNAME DIEGO_RUN_BETA true 
cf start $APPNAME
