#!/usr/bin/env bash
set -ue

APPNAME=${1:-"nora"}
STACK=${2:-"windows2012R2"}

## Remove existing
cf d -f $APPNAME

## Push new
cf push $APPNAME -s $STACK -b https://github.com/ryandotsmith/null-buildpack.git -p NoraPublished --no-start
cf set-env $APPNAME DIEGO_BETA true
cf set-env $APPNAME DIEGO_RUN_BETA true
cf enable-diego $APPNAME || echo "enable diego plugin doesn't exist. follow the instructions in the README to install it"
cf start $APPNAME
