#!/usr/bin/env bash
set -ue

APPNAME=${1:-"nora"}
STACK=${2:-"windows2012R2"}

## Remove existing
cf d -f $APPNAME

## Push new
cf push $APPNAME -s $STACK -b https://github.com/ryandotsmith/null-buildpack.git -p NoraPublished --no-start
if ! cf enable-diego $APPNAME; then
    cf add-plugin-repo CF-Community http://plugins.cloudfoundry.org/
    cf install-plugin Diego-Beta -r CF-Community
    cf enable-diego $APPNAME
fi
cf start $APPNAME
