#!/usr/bin/env bash

if ! GOARCH=amd64 GOOS=windows go build -o worker.exe worker.go; then
   echo "Cross compiling failed. If you're on MacOS, run 'brew reinstall go --with-cc-common'"
   exit 1
fi
APPNAME=${1:-"worker"}
../make_an_app . $APPNAME -c ./worker.exe -b https://github.com/cloudfoundry/binary-buildpack/releases/download/v1.0.8/binary_buildpack-cached-v1.0.8.zip
cf set-health-check worker none
cf start $APPNAME
cf logs worker --recent
