#!/usr/bin/env bash
set -uex

dir=${0%/*}
APPNAME=${1:-"wcf"}
$dir/../make_an_app $dir/Hello.Service.IIS $APPNAME -b https://github.com/greenhouse-org/hwc-buildpack/releases/download/v2.0.0/hwc-buildpack-v2.0.0.zip
cf start $APPNAME
