#!/usr/bin/env bash

set -uex

DIR=$1
APPNAME=$2
if [ "x$DIR" == "x" -o "x$APPNAME" == "x" ]; then
    echo "Usage: $0 [APPDIR] [APPNAME]"
    exit 1
fi
shift 2
STACK=${STACK:-"windows2012R2"}

## Remove existing
cf d -f $APPNAME

## Push new
cf push $APPNAME -s $STACK -b https://github.com/ryandotsmith/null-buildpack.git --no-start "$@" -p $DIR
cf curl -X PUT -d '{"diego": true}' /v2/apps/$(cf app $APPNAME --guid)
