#!/usr/bin/env bash

set -uex

DIR=$1
APPNAME=$2
if [ "x$DIR" == "x" -o "x$APPNAME" == "x" ]; then
    echo "Usage: $0 [APPDIR] [APPNAME]"
    exit 1
fi
shift 2
STACK=${STACK:-"windows2012R2"}

## Remove existing
cf d -f $APPNAME

## Push new
cf push $APPNAME -m 2g -s $STACK -b https://github.com/ryandotsmith/null-buildpack.git --no-start "$@" -p $DIR
if ! cf enable-diego $APPNAME; then
    echo "**************** Couldn't run cf enable-diego, trying to install plugin ****************"
    cf add-plugin-repo CF-Community http://plugins.cloudfoundry.org/ || \
        echo "**************** Can't add repo. Assuming repo exists ****************"
    cf install-plugin Diego-Beta -r CF-Community
    cf enable-diego $APPNAME
fi
